= TO-DO of _Glosa Internet Directory_
:author: Marcos Cruz (programandala.net)
:revdate: 2019-01-03

== 2018-12-09

Improve the "prefer" notation with a different arrow.

== 2018-12-09

Consult: It seems there's a typo in GID: the description of 'akademi'
should be '1*' instead of '*1'. It doesn't seem to mean "words not
original GEO (Clark/Ashby)", because there's also a "1" (words that
appear in one of the several "Glosa 1000" lists).

== 2018-12-09

The line breaks does not work.

The converted data is right:

----
>apparent: feno [1++G] +
>appeal: petitio [1++] +
>appear: feno [1++G]; surge [1++]; monstra se [1+]; apare [1]; gene vista [1] +
>appearance: feno [1++G] +
>appease: apaci +
>appendix: apendici [1] +
>appetite: fo-volu [1++]; apetiti [1+]; libido [1+]; apeti [1] +
>applaud: lauda [1++]; soni lauda [1+]; aplaude (prefer lauda) +
>applause: toribo [G] +
----

But the conversion to DocBook fails:

----
&gt;apparent: feno [1G]<?asciidoc-br?>
&gt;appeal: petitio [1] +
&gt;appear: feno [1G]; surge [1]; monstra se [1+]; apare [1]; gene vista [1] +
&gt;appearance: feno [1G]<?asciidoc-br?>
&gt;appease: apaci<?asciidoc-br?>
&gt;appendix: apendici [1]<?asciidoc-br?>
&gt;appetite: fo-volu [1]; apetiti [1+]; libido [1+]; apeti [1] +
&gt;applaud: lauda [1]; soni lauda [1+]; aplaude (prefer lauda)<?asciidoc-br?>
&gt;applause: toribo [G]<?asciidoc-br?>
----

And anyway `<?asciidoc-br?>` is not recognized by pandoc.

== 2018-12-11

Use dictfmt's `--headword-separator` and `--break-headwords`.

== 2018-12-22

Fix `((almost) too much)` and `((clock) time)`.

== 2019-01-03

The current dict filenames are too long:

....
dict -D

gcide      The Collaborative International Dictionary of English v.0.48
jargon     The Jargon File (version 4.4.7, 29 Dec 2003)
vera       V.E.R.A. -- Virtual Entity of Relevant Acronyms (June 2006)
fd-eng-spa English-Spanish Freedict dictionary
fd-lat-eng Latin-English Freedict dictionary
fd-eng-lat English-Latin Freedict dictionary
glosa_internet_dictionary_glosa-eng Glosa Internet Dictionary (Glosa-English)
fd-spa-eng Spanish-English Freedict dictionary
glosa_internet_dictionary_eng-glosa Glosa Internet Dictionary (English-Glosa)
....

Shorten the filenames and the titles:

....
glosa-eng  Glosa-English Dictionary 
eng-glosa  English-Glosa Dictionary
....


