// glosa.org & ne.alinome.net
:revdate: 2018-12-24

:dot: .

// Last modified 201901101537

// This text document is written in Asciidoctor format
// See http://asciidoctor.org

// About this e-book {{{1
== About this e-book

This e-book was built from the data of the
http://www.glosa.org/gid/[Glosa Internet Dictionary], the most
comprehensive Glosa dictionary.  Its initial goal was to make
the dictionary easier to use during my studying of Glosa.

There are several variants of this e-book, depending on the contents
(English-Glosa, Glosa-English or both) the layout (tables, lists or
paragraphs), and the file format (EPUB, HTML and eventually others).
The latest version of all of them, and the devolopment repository, can
be found in http://ne.alinome.net[ne alinome].

Marcos Cruz (programandala.net), 2018-12.

// Aknowledgments {{{1
== Aknowledgments

Persons who have -- more or less directly -- worked on this file:
Wendy Ashby (Glosa author), Paul Bartlett, Ron Clark (Glosa author),
Charles Ganson, Robin Gaskell, Nick Hempshall, Gary Miller, William
Patterson (former editor), Kevin Smith, Marcel Springer (maintainer of
the words list).

Sources for the words have been several publications by Ronald Clark
and Wendy Ashby, (C) Glosa Education Organization, Richmond, UK,
namely "Glosa Basic Reference", "English - Glosa 1000", "English -
Glosa 1000 classified", "Glosa 6000", "18 Steps to Fluency in
Euro-Glosa" (Glosa-English list), "Central Glosa" (lists "5000 English
to Glosa 1000" and "Useful Prefixes"), "Francais - Glosa 1000",
"Español - Glosa 1000" and others and the friendly correspondence
with Glosa author Wendy Ashby.

// Internet Links {{{1
== Internet Links

- http://www.glosa.org[The website about the Glosa language]
- http://www.glosa.org/gid/[The Glosa Internet Directory]
- http://www.glosa.org/gid/gidhist.htm[History of the Glosa Internet
  Directory]
- http://ne.alinome.net[ne alinome], the website of this e-book and
  other similar Glosa projects.

// Usage {{{1
== Usage

The dictionary has three levels:

1. "Core" (or "Centra", small)   = marked with `++`
2. "Basic" (or "Basi", middle)   = marked with `++` and `+`
3. "Literary" (or "Mega", large) = all words

Suggestion: prefer words with `++`, then take `+`.

Abbreviations:

|===
| `++`  | words from Core Glosa (first level of the dictionary)
| `+`   | additional words from Basic Glosa (second level of the dictionary)
| `1`   | words that appear in one of the several "Glosa 1000" lists
| `1*`  | words slightly modificated from Glosa-1000-words
| `*`   | words not original Glosa Education Organization (Clark/Ashby)
| `X`   | words to be avoided; in parens, the prefered synonym
| `G`   | words with Greek origin
| `adj` | adjective
| `n`   | noun
| `v`   | verb
|===
