= Glosa Internet Dictionary
:revdate: 2018-12-09

// Last modified 201812091639

// This text document is written in Asciidoctor format
// See http://asciidoctor.org

// About this e-book {{{1
== About this e-book

This book contains a copy of the http://www.glosa.org/gid/[Glosa
Internet Dictionary], last updated on 2013-04-30 by its current
maintainer, Marcel Springer.

The goal of this book was to make the dictionary easier to use during
my studying of Glosa.

Marcos Cruz (programandala.net), 2018-12.

// Aknowledgments {{{1
== Aknowledgments

Persons who have -- more or less directly -- worked on this file:
Wendy Ashby (Glosa author), Paul Bartlett, Ron Clark (Glosa author),
Charles Ganson, Robin Gaskell, Nick Hempshall, Gary Miller, William
Patterson (former editor), Kevin Smith, Marcel Springer (maintainer of
the words list).

Sources for the words have been several publications by Ronald Clark
and Wendy Ashby, (C) Glosa Education Organization, Richmond, UK,
namely "Glosa Basic Reference", "English - Glosa 1000", "English -
Glosa 1000 classified", "Glosa 6000", "18 Steps to Fluency in
Euro-Glosa" (Glosa-English list), "Central Glosa" (lists "5000 English
to Glosa 1000" and "Useful Prefixes"), "Francais - Glosa 1000",
"Español - Glosa 1000" and others and the friendly correspondence
with Glosa author Wendy Ashby.

// Internet Links {{{1
== Internet Links

- http://www.glosa.org[Information on the Glosa language]
- http://www.glosa.org/gid/[The Glosa Internet Directory]
- http://www.glosa.org/gid/gidhist.htm[History of the Glosa Internet
  Directory]

// Usage {{{1
== Usage

The dictionary has three levels:

1. "Core" (or "Centra", small)   = marked with `++`
2. "Basic" (or "Basi", middle)   = marked with `++` and `+`
3. "Literary" (or "Mega", large) = all words

Suggestion: prefer words with "++", then take "+".

Other abbreviations:

`G`:: Glosa words with Greek origin
`1`:: "Glosa 1000" (words that appear in one of the several "Glosa 1000" lists)
`*`:: words not original GEO (Clark/Ashby)
`1*`:: words slightly modificated from Glosa-1000-words
`X`:: words to be avoided; in brackets, the prefered synonym
`adj`:: adjective
`n`:: noun
`v`:: verb

